labels_rf:
  0: 'nolabel'
  100: 'clear'
  101: 'rain'
  102: 'fog'
labels_s:
  0 : "clear"
  1 : "snow"
  9 : "nolabel"
labels:
  0: 'nolabel'
  1: 'clear'
  2: 'rain'
  3: 'fog'
  4: 'snow'
learning_map_rf:
  0: 0
  100: 1
  101: 2
  102: 3
learning_map_s:
  0: 1
  1: 4
  9: 0

